from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('master/user/', views.user_index, name='user-index'),
    path('master/user/add/', views.user_add, name='user-add'),
    path('master/user/view/<str:_id>/', views.user_view, name='user-view'),
    path('master/user/update/<str:_id>/',
         views.user_update, name='user-update'),
    path('master/user/delete/<str:_id>/',
         views.user_delete, name='user-delete'),
    path('master/user/change-password/',
         views.change_password, name='change-password'),
    path('master/user/set-password/<str:_id>/',
         views.set_password, name='set-password'),
    path('master/user-area/view/<str:_id>/',
         views.user_area_view, name='user-area-view'),
    path('master/distributor/', views.distributor_index, name='distributor-index'),
    path('master/distributor/add/', views.distributor_add, name='distributor-add'),
    path('master/distributor/view/<str:_id>/',
         views.distributor_view, name='distributor-view'),
    path('master/distributor/update/<str:_id>/',
         views.distributor_update, name='distributor-update'),
    path('master/distributor/delete/<str:_id>/',
         views.distributor_delete, name='distributor-delete'),
    path('master/area-sales/', views.area_sales_index, name='area-sales-index'),
    path('master/area-sales/add/', views.area_sales_add, name='area-sales-add'),
    path('master/area-sales/view/<str:_id>/',
         views.area_sales_view, name='area-sales-view'),
    path('master/area-sales/update/<str:_id>/',
         views.area_sales_update, name='area-sales-update'),
    path('master/area-sales/delete/<str:_id>/',
         views.area_sales_delete, name='area-sales-delete'),
    path('master/area-sales-detail/delete/<str:_id>/<str:_distributor>/',
         views.area_sales_detail_delete, name='area-sales-detail-delete'),
    path('master/position/', views.position_index, name='position-index'),
    path('master/position/add/', views.position_add, name='position-add'),
    path('master/position/view/<str:_id>/',
         views.position_view, name='position-view'),
    path('master/position/update/<str:_id>/',
         views.position_update, name='position-update'),
    path('master/position/delete/<str:_id>/',
         views.position_delete, name='position-delete'),
    path('master/menu/', views.menu_index, name='menu-index'),
    path('master/menu/add/', views.menu_add, name='menu-add'),
    path('master/menu/view/<str:_id>/', views.menu_view, name='menu-view'),
    path('master/menu/update/<str:_id>/',
         views.menu_update, name='menu-update'),
    path('master/menu/delete/<str:_id>/',
         views.menu_delete, name='menu-delete'),
    path('master/auth/update/<str:_id>/<str:_menu>/',
         views.auth_update, name='auth-update'),
    path('master/auth/delete/<str:_id>/<str:_menu>/',
         views.auth_delete, name='auth-delete'),
    path('master/area-user/delete/<str:_id>/<str:_area>/',
         views.area_user_delete, name='area-user-delete'),
    path('master/channel/', views.channel_index, name='channel-index'),
    path('master/channel/add/', views.channel_add, name='channel-add'),
    path('master/channel/view/<str:_id>/',
         views.channel_view, name='channel-view'),
    path('master/channel/update/<str:_id>/',
         views.channel_update, name='channel-update'),
    path('master/channel/delete/<str:_id>/',
         views.channel_delete, name='channel-delete'),
    path('master/area-channel/', views.area_channel_index,
         name='area-channel-index'),
    path('master/area-channel/add/',
         views.area_channel_add, name='area-channel-add'),
    path('master/area-channel/view/<str:_id>/',
         views.area_channel_view, name='area-channel-view'),
    path('master/area-channel/delete/<str:_id>/',
         views.area_channel_delete, name='area-channel-delete'),
    path('master/area-channel-detail/update/<str:_id>/<str:_channel>/',
         views.area_channel_detail_update, name='area-channel-detail-update'),
    path('anp/budget/', views.budget_index, name='budget-index'),
    path('anp/budget/add/<str:_area>/', views.budget_add, name='budget-add'),
    path('anp/budget/view/<path:_id>/<str:_msg>/',
         views.budget_view, name='budget-view'),
    path('anp/budget/update/<path:_id>/',
         views.budget_update, name='budget-update'),
    path('anp/budget/delete/<path:_id>/',
         views.budget_delete, name='budget-delete'),
    path('anp/budget_detail/update/<path:_id>/',
         views.budget_detail_update, name='budget-detail-update'),
    path('anp/budget_upload/', views.budget_upload, name='budget-upload'),
]
