from django.urls import path
from . import views

urlpatterns = [
     path('', views.home, name='home'),
     path('master/user/', views.user_index, name='user-index'),
     path('master/user/add/', views.user_add, name='user-add'),
     path('master/user/view/<int:_id>/', views.user_update, name='user-view'),
     path('master/user/delete/<int:_id>/',
          views.user_delete, name='user-delete'),
     path('master/user/change-password/',
          views.change_password, name='change-password'),
     path('master/user/set-password/<int:_id>/',
          views.set_password, name='set-password'),
     path('setup/', views.setup, name='setup'),
     path('master/cabang/', views.cab_index, name='cab-index'),
     path('master/cabang/add/', views.cab_add, name='cab-add'),
     path('master/cabang/view/<int:_id>/', views.cab_update, name='cab-view'),
     path('master/cabang/delete/<int:_id>/',
         views.cab_delete, name='cab-delete'),
     path('master/paket/', views.paket_index, name='paket-index'),
     path('master/paket/add/', views.paket_add, name='paket-add'),
     path('master/paket/view/<int:_id>/', views.paket_update, name='paket-view'),
     path('master/paket/delete/<int:_id>/',
         views.paket_delete, name='paket-delete'),
     path('master/kategori/', views.kategori_item_index, name='kat-item-index'),
     path('master/kategori/add/', views.kategori_item_add, name='kat-item-add'),
     path('master/kategori/view/<int:_id>/',
          views.kategori_item_update, name='kat-item-view'),
     path('master/kategori/delete/<int:_id>/', views.kategori_item_delete, name='kat-item-delete'),
]
