# Generated by Django 4.2.6 on 2023-11-04 01:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AreaChannel',
            fields=[
                ('area_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaSales',
            fields=[
                ('area_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('budget_year', models.CharField(max_length=4)),
                ('budget_month', models.CharField(max_length=2)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_upping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_status', models.CharField(default='OPEN', max_length=5)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('budget_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.areasales')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('distributor_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('distributor_name', models.CharField(max_length=50)),
                ('sap_code', models.CharField(max_length=50, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.CharField(help_text='Max 3 digits Position shortname.', max_length=3, primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_upping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_proposed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_program', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_claim', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.budget')),
                ('budget_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.channel')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.distributor'),
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AreaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.areasales')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AreaSalesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.areasales')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='AreaChannelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.areachannel')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.channel')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.position'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='budgetdetail',
            constraint=models.UniqueConstraint(fields=('budget', 'budget_channel'), name='unique_budget_channel'),
        ),
        migrations.AddConstraint(
            model_name='auth',
            constraint=models.UniqueConstraint(fields=('user', 'menu'), name='unique_user_menu'),
        ),
        migrations.AddConstraint(
            model_name='areauser',
            constraint=models.UniqueConstraint(fields=('area', 'user'), name='unique_area_user'),
        ),
        migrations.AddConstraint(
            model_name='areasalesdetail',
            constraint=models.UniqueConstraint(fields=('area', 'distributor'), name='unique_area_distributor'),
        ),
        migrations.AddConstraint(
            model_name='areachanneldetail',
            constraint=models.UniqueConstraint(fields=('area', 'channel'), name='unique_area_channel'),
        ),
    ]
