# Generated by Django 4.2.6 on 2023-11-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdetail',
            name='budget_percent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
