# Generated by Django 5.0 on 2024-05-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomemessage',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
