# Generated by Django 4.2.4 on 2023-10-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='entry_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_date',
        ),
    ]
