# Generated by Django 5.0.6 on 2024-06-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_welcomemessage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='invoice',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
