# Generated by Django 4.2.6 on 2023-11-06 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_budgetdetail_budget_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('approver1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver1', to=settings.AUTH_USER_MODEL)),
                ('approver2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver2', to=settings.AUTH_USER_MODEL)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.areasales')),
            ],
        ),
    ]
