# Generated by Django 5.0.6 on 2026-03-04 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_welcomemessage_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proposalrelease',
            name='unique_proposal_approval',
        ),
    ]
