# Generated by Django 4.2.4 on 2023-10-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='distributor_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
