# Generated by Django 4.2.4 on 2023-09-04 06:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_setup_telp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
                ('kota', models.EmailField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('telp', phonenumber_field.modelfields.PhoneNumberField(
                    max_length=128, region=None)),
                ('manager', models.CharField(max_length=50)),
                ('rekening_1', models.CharField(max_length=50)),
                ('atas_nama_1', models.CharField(max_length=50)),
                ('bank_1', models.CharField(max_length=50)),
                ('rekening_2', models.CharField(max_length=50)),
                ('atas_nama_2', models.CharField(max_length=50)),
                ('bank_2', models.CharField(max_length=50)),
            ],
        ),
    ]
