# Generated by Django 5.0 on 2024-02-01 18:04

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_region_regiondetail_regiondetail_unique_region_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='approval',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
