# Generated by Django 5.0.6 on 2026-03-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_proposalrelease_unique_proposal_approval'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programrelease',
            name='unique_program_approval',
        ),
    ]
