# Generated by Django 5.0 on 2024-01-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_proposal_claim_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('return_to', models.BooleanField(default=False)),
                ('limit', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('approve', models.BooleanField(default=False)),
                ('revise', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
                ('notif', models.BooleanField(default=False)),
                ('as_approved', models.CharField(max_length=15, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.areasales')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.channel')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.position')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_approval_id', models.CharField(max_length=50, null=True)),
                ('claim_approval_name', models.CharField(max_length=50, null=True)),
                ('claim_approval_email', models.CharField(max_length=50, null=True)),
                ('claim_approval_position', models.CharField(max_length=50, null=True)),
                ('claim_approval_date', models.DateTimeField(null=True)),
                ('claim_approval_status', models.CharField(default='N', max_length=1)),
                ('sequence', models.IntegerField(default=0)),
                ('limit', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('return_to', models.BooleanField(default=False)),
                ('revise_note', models.CharField(max_length=200, null=True)),
                ('return_note', models.CharField(max_length=200, null=True)),
                ('reject_note', models.CharField(max_length=200, null=True)),
                ('mail_sent', models.BooleanField(default=False)),
                ('approve', models.BooleanField(default=False)),
                ('revise', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
                ('notif', models.BooleanField(default=False)),
                ('as_approved', models.CharField(max_length=15, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.claim')),
            ],
        ),
        migrations.AddConstraint(
            model_name='claimmatrix',
            constraint=models.UniqueConstraint(fields=('area', 'channel', 'approver'), name='unique_claim_approver'),
        ),
        migrations.AddConstraint(
            model_name='claimrelease',
            constraint=models.UniqueConstraint(fields=('claim', 'claim_approval_id'), name='unique_claim_approval'),
        ),
    ]
