# Generated by Django 4.2.4 on 2023-10-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_user_entry_by_user_entry_date_user_update_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasales',
            name='entry_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areasales',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='areasales',
            name='update_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areasales',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='areasalesdetail',
            name='entry_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areasalesdetail',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='areasalesdetail',
            name='update_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areasalesdetail',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='entry_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='update_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='entry_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='update_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
    ]
