# Generated by Django 4.2.4 on 2023-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_cabang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabang',
            name='kota',
            field=models.CharField(max_length=50),
        ),
    ]
