# Generated by Django 4.2.6 on 2023-11-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_budgetapproval'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budgetapproval',
            constraint=models.UniqueConstraint(fields=('area', 'approver'), name='unique_area_approver'),
        ),
    ]
