# Generated by Django 4.2.6 on 2023-11-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_budgetapproval_unique_area_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetApprovalRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.areasales')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.position')),
            ],
        ),
        migrations.AddConstraint(
            model_name='budgetapprovalrules',
            constraint=models.UniqueConstraint(fields=('area', 'position'), name='unique_area_position'),
        ),
    ]
