# Generated by Django 5.0 on 2024-01-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_claimmatrix_claimrelease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
