# Generated by Django 4.2.4 on 2023-10-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_areasales_entry_by_areasales_entry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areasalesdetail',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='areasalesdetail',
            old_name='distributor_id',
            new_name='distributor',
        ),
    ]
