# Generated by Django 4.2.4 on 2023-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_cabang_kota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabang',
            name='alamat',
            field=models.CharField(max_length=150),
        ),
    ]
