# Generated by Django 5.0 on 2024-02-11 21:17

import apps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_proposal_attachment_proposalattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalattachment',
            name='attachment',
            field=models.FileField(null=True, upload_to='proposal/', validators=[apps.validators.file_size]),
        ),
    ]
