# Generated by Django 5.0.6 on 2026-03-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_programrelease_unique_program_approval'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='claimrelease',
            name='unique_claim_approval',
        ),
    ]
