# Generated by Django 5.0 on 2024-01-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_claim_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='seq_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(default='PENDING', max_length=15),
        ),
    ]
