# Generated by Django 5.0.6 on 2026-03-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_claimrelease_unique_claim_approval'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clrelease',
            name='unique_cl_approval',
        ),
    ]
