# Generated by Django 4.2.4 on 2023-09-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_paket'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
    ]
