# Generated by Django 5.0 on 2024-01-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_claim_seq_number_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='entry_pos',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
