# Generated by Django 4.2.6 on 2023-11-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_delete_budgetapprovalrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='a1_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='a1_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='a1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='a1_position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='a1_status',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='a2_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='a2_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='a2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='a2_position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='a2_status',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
