# Generated by Django 5.0 on 2024-01-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_claim_entry_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_claim',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
