# Generated by Django 4.2.4 on 2023-09-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_kategoriitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_kategori', to='apps.kategoriitem')),
            ],
        ),
    ]
