# Generated by Django 5.0 on 2024-02-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auth_submit_budgettransfer_seq_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(default='DRAFT', max_length=15),
        ),
    ]
