# Generated by Django 4.2.6 on 2023-11-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_budget_a1_date_remove_budget_a1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrelease',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
