# Generated by Django 5.0 on 2024-01-11 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_proposal_proposal_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='additional_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='additional_proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_proposal', to='apps.proposal'),
        ),
    ]
