# Generated by Django 4.2.6 on 2023-11-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_budgetrelease_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_status',
            field=models.CharField(default='DRAFT', max_length=5),
        ),
    ]
