# Generated by Django 5.0 on 2024-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_period',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
