# Generated by Django 5.0 on 2024-01-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_claim_additional_amount_claim_additional_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='additional_proposal',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
