# Generated by Django 4.2.6 on 2023-11-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_budget_budget_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_status',
            field=models.CharField(default='DRAFT', max_length=10),
        ),
    ]
