# Generated by Django 5.0 on 2024-01-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_claim_total_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimList',
            fields=[
                ('cl_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cl_date', models.DateTimeField(null=True)),
                ('cl_status', models.CharField(default='PENDING', max_length=15)),
                ('seq_number', models.IntegerField(default=0)),
                ('entry_pos', models.CharField(max_length=5, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.claimlist')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.claim')),
            ],
        ),
        migrations.AddConstraint(
            model_name='claimlistdetail',
            constraint=models.UniqueConstraint(fields=('claim', 'cl_id'), name='unique_claim_list'),
        ),
    ]
