# Generated by Django 5.0 on 2024-01-17 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_claimlist_claimlistdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimListMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('return_to', models.BooleanField(default=False)),
                ('limit', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('approve', models.BooleanField(default=False)),
                ('revise', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
                ('notif', models.BooleanField(default=False)),
                ('as_approved', models.CharField(max_length=15, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.areasales')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.channel')),
                ('cl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.claimlist')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.position')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimListRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_approval_id', models.CharField(max_length=50, null=True)),
                ('cl_approval_name', models.CharField(max_length=50, null=True)),
                ('cl_approval_email', models.CharField(max_length=50, null=True)),
                ('cl_approval_position', models.CharField(max_length=50, null=True)),
                ('cl_approval_date', models.DateTimeField(null=True)),
                ('cl_approval_status', models.CharField(default='N', max_length=1)),
                ('sequence', models.IntegerField(default=0)),
                ('limit', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('return_to', models.BooleanField(default=False)),
                ('revise_note', models.CharField(max_length=200, null=True)),
                ('return_note', models.CharField(max_length=200, null=True)),
                ('reject_note', models.CharField(max_length=200, null=True)),
                ('mail_sent', models.BooleanField(default=False)),
                ('approve', models.BooleanField(default=False)),
                ('revise', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
                ('notif', models.BooleanField(default=False)),
                ('as_approved', models.CharField(max_length=15, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('entry_by', models.CharField(blank=True, max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.claimlist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='claimlistmatrix',
            constraint=models.UniqueConstraint(fields=('cl_id', 'area', 'channel', 'approver'), name='unique_claim_list_approver'),
        ),
        migrations.AddConstraint(
            model_name='claimlistrelease',
            constraint=models.UniqueConstraint(fields=('cl_id', 'cl_approval_id'), name='unique_claim_list_approval'),
        ),
    ]
