# Generated by Django 4.2.6 on 2023-11-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_budget_budget_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_status',
            field=models.CharField(default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_upping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
