# Generated by Django 5.0 on 2024-01-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_claimlistmatrix_claimlistrelease_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimlist',
            name='cl_status',
        ),
        migrations.AddField(
            model_name='claimlist',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.areasales'),
        ),
        migrations.AddField(
            model_name='claimlist',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.distributor'),
        ),
        migrations.AddField(
            model_name='claimlist',
            name='status',
            field=models.CharField(default='DRAFT', max_length=15),
        ),
    ]
