# Generated by Django 5.0 on 2024-02-25 10:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_claim_depo'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='footer',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
