# Generated by Django 5.0 on 2024-02-25 17:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_program_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='disclaimer',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
