# Generated by Django 5.0 on 2024-01-17 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_remove_claimlist_cl_status_claimlist_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimlist',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.channel'),
        ),
    ]
