# Generated by Django 5.0 on 2024-02-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_program_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='additional',
            field=models.BooleanField(default=False),
        ),
    ]
