# Generated by Django 5.0 on 2024-01-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_claimlist_channel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaimList',
            new_name='CL',
        ),
        migrations.RenameModel(
            old_name='ClaimListDetail',
            new_name='CLDetail',
        ),
        migrations.RenameModel(
            old_name='ClaimListMatrix',
            new_name='CLMatrix',
        ),
        migrations.RenameModel(
            old_name='ClaimListRelease',
            new_name='CLRelease',
        ),
        migrations.RemoveConstraint(
            model_name='clmatrix',
            name='unique_claim_list_approver',
        ),
        migrations.RemoveConstraint(
            model_name='clrelease',
            name='unique_claim_list_approval',
        ),
        migrations.AddConstraint(
            model_name='clmatrix',
            constraint=models.UniqueConstraint(fields=('cl_id', 'area', 'channel', 'approver'), name='unique_cl_approver'),
        ),
        migrations.AddConstraint(
            model_name='clrelease',
            constraint=models.UniqueConstraint(fields=('cl_id', 'cl_approval_id'), name='unique_cl_approval'),
        ),
    ]
