# Generated by Django 5.0 on 2024-02-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_proposal_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_tax',
            field=models.BooleanField(default=False),
        ),
    ]
