# Generated by Django 5.0 on 2024-01-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_rename_claimlist_cl_rename_claimlistdetail_cldetail_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clmatrix',
            name='unique_cl_approver',
        ),
        migrations.RemoveField(
            model_name='clmatrix',
            name='cl_id',
        ),
        migrations.AddConstraint(
            model_name='clmatrix',
            constraint=models.UniqueConstraint(fields=('area', 'channel', 'approver'), name='unique_cl_approver'),
        ),
    ]
