# Generated by Django 4.2.6 on 2023-11-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_budget_budget_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrelease',
            name='budget_approval_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
