# Generated by Django 4.2.6 on 2023-11-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_budgetrelease_budget_approval_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrelease',
            name='percentage_note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='budgetrelease',
            name='upping_note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
