# Generated by Django 5.0 on 2024-02-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_claim_is_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdetail',
            name='budget_transfer_minus',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='budgetdetail',
            name='budget_transfer_plus',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='budgettransfer',
            name='status',
            field=models.CharField(default='DRAFT', max_length=15),
        ),
    ]
