# Generated by Django 5.0 on 2024-03-16 07:02

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_budgetdetail_budget_transfer_minus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='header',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
