# Generated by Django 4.2.6 on 2023-11-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_budgetrelease_percentage_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrelease',
            name='return_note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
