# Generated by Django 4.2.6 on 2023-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_budgetrelease_return_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('document', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year_closed', models.CharField(max_length=4)),
                ('month_closed', models.CharField(max_length=2)),
                ('year_open', models.CharField(max_length=4)),
                ('month_open', models.CharField(max_length=2)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
