# Generated by Django 5.0 on 2024-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_remove_proposal_additional_proposal_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='actual_claim',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
