# Generated by Django 4.2.6 on 2023-11-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_budget_unique_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdetail',
            name='budget_month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='budgetdetail',
            name='budget_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
