# Generated by Django 5.0 on 2024-03-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_proposal_actual_claim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='actual_claim',
            new_name='parked_claim',
        ),
    ]
