# Generated by Django 5.0 on 2024-03-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_rename_actual_claim_proposal_parked_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdetail',
            name='budget_remaining',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
