# Generated by Django 4.2.6 on 2023-11-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_remove_budget_unique_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('proposal_date', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=1)),
                ('channel', models.CharField(max_length=5)),
                ('program_name', models.CharField(max_length=200)),
                ('products', models.TextField()),
                ('area', models.CharField(max_length=50)),
                ('period_start', models.DateTimeField(null=True)),
                ('period_from', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(default=0)),
                ('objectives', models.TextField()),
                ('mechanism', models.TextField()),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('attachment', models.CharField(max_length=200, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.budget')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.division')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='IncrementalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('swop_carton', models.IntegerField(default=0)),
                ('swop_nom', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('swp_carton', models.IntegerField(default=0)),
                ('swp_nom', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.proposal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectedcost',
            constraint=models.UniqueConstraint(fields=('proposal', 'activities'), name='unique_proposal_activities'),
        ),
        migrations.AddConstraint(
            model_name='incrementalsales',
            constraint=models.UniqueConstraint(fields=('proposal', 'product'), name='unique_proposal_product'),
        ),
    ]
