# Generated by Django 5.0 on 2024-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_budgetdetail_budget_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incrementalsales',
            name='incpst_carton',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incrementalsales',
            name='incpst_nom',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12),
        ),
    ]
