# Generated by Django 5.0 on 2024-05-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_alter_incrementalsales_incpst_carton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incrementalsales',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
