# Generated by Django 4.2.6 on 2023-11-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_division_proposal_projectedcost_incrementalsales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='division_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
