# Generated by Django 4.2.6 on 2023-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_alter_division_division_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
