# Generated by Django 4.2.6 on 2023-11-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_proposal_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incrementalsales',
            name='area',
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(default='DRAFT', max_length=15),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='type',
            field=models.CharField(default='B', max_length=1),
        ),
    ]
