# Generated by Django 4.2.6 on 2023-11-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_remove_incrementalsales_area_proposal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='seq_number',
            field=models.IntegerField(default=0),
        ),
    ]
